# Basic settings.
server.port: 8080
spring.mvc.favicon.enabled: false

# Profiles settings.
spring.profiles.active: h2, logging

---

spring.profiles: mysql

# DB settings.
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_repo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root1234
    schema: null

---

spring.profiles: h2

# DB settings.
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_repo
    schema: classpath:schema.sql

---

spring.profiles: logging

# Logging settings.
logging:
  level.root: INFO
  file: amazing_log.log
